---
engines:
  checkstyle:
    enabled: true
    channel: beta
    checks:
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck:
        enabled: false
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: beta
ratings:
  paths:
  - "**.java"
exclude_paths: []
